env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
  -
    id: "glow"
    binary: glow
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
  -
    id: "darwin"
    binary: "glow"
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: default
    builds:
      - glow
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      386: i386
      amd64: x86_64
  - id: darwin
    builds:
      - darwin
    replacements:
      darwin: Darwin
      amd64: x86_64

nfpm:
  vendor: charmbracelet
  homepage: "https://charm.sh/"
  maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
  description: "Render markdown on the CLI"
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin

brews:
  - ids:
    - darwin
    github:
      owner: charmbracelet
      name: homebrew-tap
    commit_author:
      name: "Christian Muehlhaeuser"
      email: "muesli@gmail.com"
    homepage: "https://charm.sh/"
    description: "Render markdown on the CLI"
    # skip_upload: true

sign:
  artifacts: checksum

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
